### ISSUE TITLE
Causes ESLint to be installed in ESLint

### ISSUE THREAD

**Issue by IanVS** [eslint/eslint-plugin-markdown#10]
Because of the peer dependency on ESLint, when this plugin is installed within ESLint, ESLint becomes a dependency of itself.  Is there any way to avoid that?

**Comment by btmills** [comment]
I think this is correct. Hypothetical: ESLint 2.0 makes a breaking change to the plugin API. Until it's updated, this plugin still wants to reference ESLint 1.x, which it will still have thanks to the dependency.

**Comment by IanVS** [comment]
Ok, sounds reasonable.
