### ISSUE TITLE
Getting it to work in VSCode?

### ISSUE THREAD

**Issue by greggman** [eslint/eslint-plugin-markdown#112]
I installed eslint-plugin-markdown in a project I'm editing with VScode and ran into issues

First I added the suggested overrides then I checked for errors in a markdown file, no errors show even thought I put intentional errors.

```
{
  ...
  "overrides": [
    {
      "files": [ "**/*.md" ],
      "parserOptions": {
        "ecmaFeatures": {
            "impliedStrict": true
        },
      },
      "rules": {
        "strict": "off"
      }
    }
  ]
}
```

I tried adding `"markdown"` to the `eslint.validate` setting as in in `<projectfolder>/.vscode/settings.json`

```
{
  "eslint.validate": [ "javascript", "html", "markdown" ]
}
```

But in that case VSCode seems be trying to lint the entire markdown file as JavaScript. I get errors on the entire file starting with the first line which is just normal text.

Any idea what I'm doing wrong?

**Comment by btmills** [comment]
I'm able to reproduce something like this with a configuration similar to yours, though I removed the `overrides`:

<details open>
<p><summary><code>.vscode/settings.json</code></summary></p>
<pre><code>{
    "eslint.validate": ["javascript", "markdown"]
}</code></pre>
</details>

<details open>
<p><summary><code>.eslintrc.js</code></summary></p>
<pre><code>module.exports = {
    plugins: [
    "markdown"
    ],
    extends: [
        "eslint:recommended"
    ],
    env: {
        browser: true
    }
}</code></pre>
</details>

In my case, lint rule failures are shown correctly:

![screenshot 2019-01-02 14 46 58](https://user-images.githubusercontent.com/1709537/50609291-42824a00-0e9d-11e9-9178-25cf1b796545.png)

But for some reason, syntax errors are all shown on the first line:

![screenshot 2019-01-02 14 49 20](https://user-images.githubusercontent.com/1709537/50609434-95f49800-0e9d-11e9-8da0-f9c40ca6e136.png)

It got the column (7) correct, but ignored the line. Running ESLint outside the integration returns the correct line and column:

```sh
$ node_modules/.bin/eslint README.md

/Users/brandon/code/eslint/markdown-test/README.md
  5:7  error  Parsing error: Unexpected token !

✖ 1 problem (1 error, 0 warnings)
```

I don't get any errors in a file that shouldn't have any:

![screenshot 2019-01-02 14 56 18](https://user-images.githubusercontent.com/1709537/50609740-9ccfda80-0e9e-11e9-9aab-2151768a1ece.png)

Does this match what you're seeing?

**Comment by greggman** [comment]
Actually now that you mention it yes, that's what I'm seeing but it's not just syntax errors, it's any eslint error.

Here the only error is a style error, spaces after `foo`

<img width="236" alt="screen shot 2019-01-03 at 10 52 02" src="https://user-images.githubusercontent.com/234804/50620876-a7917a80-0f45-11e9-9bfb-fc8339461e1e.png">

with the space removed

<img width="251" alt="screen shot 2019-01-03 at 10 52 11" src="https://user-images.githubusercontent.com/234804/50620879-abbd9800-0f45-11e9-8d64-8c106b33e277.png">

**Comment by btmills** [comment]
I finally figured out what was causing this! Most ESLint rules pass both start and end locations, but parse errors only specify start locations. A bug was causing the processor to add `endLine: NaN` to those messages, which was understandably confusing VSCode. I opened #154 to fix this.

**Comment by mightyiam** [comment]
:heart_eyes:
