### ISSUE TITLE
Using 'await' outside 'async' functions

### ISSUE THREAD

**Issue by m-murasovs** [eslint/eslint-plugin-markdown#162]
I have solitary code examples such as `const foo = await bar()`, which cause the `Parsing error: Can not use keyword 'await' outside an async function`

I cannot find a rule to disable this. 

Any tips?

Thanks!

**Comment by btmills** [comment]
Top-level `await` is still a [stage 3 experimental syntax proposal](https://github.com/tc39/proposals). ESLint will support it natively [when it reaches stage 4](https://github.com/eslint/eslint#what-about-experimental-features) and becomes part of the language standard. Until then, we recommend [using an external parser](https://eslint.org/docs/user-guide/configuring#specifying-parser) that supports this syntax, like [`@babel/eslint-parser`](https://github.com/babel/babel/tree/main/eslint/babel-eslint-parser). (You may also need [`@babel/plugin-syntax-top-level-await`](https://babeljs.io/docs/en/babel-plugin-syntax-top-level-await).)
