### ISSUE TITLE
Update remark-parse dependency

### ISSUE THREAD

**Issue by bicrypt** [eslint/eslint-plugin-markdown#186]
The currently installed version of remark-parse uses a version of "trim" that is marked "high severity" by npm!

https://www.npmjs.com/advisories/1700

The latest version of [remark-parse](https://www.npmjs.com/package/remark-parse) does not depend on this dangerous dependency.

Thanks in advance!

**Comment by dominikg** [comment]
may not be easy to do, see https://github.com/eslint/eslint-plugin-markdown/pull/171#issuecomment-826390279 and https://github.com/eslint/eslint-plugin-markdown/pull/175

**Comment by btmills** [comment]
Upgrading to `mdast-util-from-markdown` might not be quite as difficult as originally feared. I have a prototype implementation that actually uncovered two incorrect assertions in the existing tests! I'll need to do more testing to be confident enough to submit a PR, but early signs are encouraging.
