### ISSUE TITLE
Typescript examples are not working / out of date

### ISSUE THREAD

**Issue by David-Else** [eslint/eslint-plugin-markdown#189]
Seems the TypeScript examples are not compatible with the current version:

https://github.com/eslint/eslint-plugin-markdown/tree/main/examples/typescript

@btmills ?

**Comment by btmills** [comment]
Can you provide more information? What have you done, and what are you observing?

**Comment by btmills** [comment]
The examples are tested as part of every PR, so they should be all good! If you’re using the v2 release candidate, you should be able to upgrade to the v2 final without issue.

**Comment by David-Else** [comment]
Thanks, I updated and all is well :)
