### ISSUE TITLE
Allow `jsx` info strings

### ISSUE THREAD

**Issue by IanVS** [eslint/eslint-plugin-markdown#19]
The code blocks in [jsx-quotes](http://eslint.org/docs/rules/jsx-quotes) would be better expressed as `jsx` rather than `js`

`js`:
```js
<a b='c' />
```

`jsx`:
```jsx
<a b='c' />
```

But this would require supporting `jsx` info strings in this plugin.  Ideally, would the pre-processor also be able to add the `jsx` ecmaFeature? Otherwise, linting of these will need to wait until https://github.com/eslint/eslint/issues/3698.

**Comment by btmills** [comment]
I don't think it's possible for a preprocessor to alter configuration, so let's wait for the comment there. However, we can definitely add `jsx` to the list of info strings.
