### ISSUE TITLE
feat: option to ignore certain languages

### ISSUE THREAD

**Issue by privatenumber** [eslint/eslint-plugin-markdown#201]
## Problem
This plugin creates a virtual file for every code block in a markdown, but sometimes it is not preferable to lint every block.

In my case, I want to lint all JS codeblocks, but not TS. However, since my ESlint config has an override for `.ts` files, it will lint the `ts` codeblocks in my markdown files.

I prefer not to manually disable very rule for `**/*.md/*.ts` in an override, or add a skip comment to each `ts` block.

## Reproduction steps
Given this setup (derived from the README), it will create virtual files for every codeblock in a markdown:
```js
module.exports = {
    overrides: [
        {
            files: "*.md",
		    plugins: ["markdown"],
            processor: "markdown/markdown"
        },
    ]
};
```

Currently, I only want to lint `js` codeblocks, but because I [lint `ts` files](https://github.com/privatenumber/eslint-config/blob/edbf3e2ab375db633053bb2e458a121e86e1aaa7/rules/typescript.js#L32), the `ts` codeblocks get linted too.

## Feature request
A `ignoreLang` option where an array of languages can be specified to ignore.

**Comment by btmills** [comment]
I can see how disabling every rule in `ts` code blocks or manually adding skip comments would quickly become annoying. Are you able to add `**/*.md/*.ts` to [`ignorePatterns`](https://eslint.org/docs/user-guide/configuring/ignoring-code#ignorepatterns-in-config-files) in your `.eslintrc`?

**Comment by privatenumber** [comment]
I tried adding it to `ignorePatterns` but didn't seem to work.

**Comment by btmills** [comment]
Are you able to put together an example repository for me to try? It's possible virtual filenames from code blocks aren't checked against `ignorePatterns`, which might be a bug.

We're working on a [new config format](https://github.com/eslint/rfcs/tree/main/designs/2019-config-simplification) to address the complications of the `.eslintrc` format. We'll want to be sure we think about how virtual filenames from code blocks interact with `ignores` patterns.

**Comment by nzakas** [comment]
Closing due to age.

**Comment by jeremymeng** [comment]
Has anyone found a reasonable workaround?

**Comment by btmills** [comment]
@jeremymeng you should be able to add `**/*.md/*.ts` to [`ignorePatterns`](https://eslint.org/docs/user-guide/configuring/ignoring-code#ignorepatterns-in-config-files) in your `.eslintrc`.

**Comment by jeremymeng** [comment]
Maybe our scenario is a bit complicated, and I am not sure what went wrong: we have an override for ts files that specifies ts projects:
```json
  ignorePatterns: ["**/generated/**", "**/*.md/*.{ts,json}"],                                                                                                                                                                  
  "overrides": [                                                                                                                                                                                                               
    {                                                                                                                                                                                                                          
      files: ['*.ts', '*.tsx', '*.json'],                                                                                                                                                                                      
      parser: "@typescript-eslint/parser",                                                                                                                                                                                     
      parserOptions: {                                                                                                                                                                                                         
        project: [                                                                                                                                                                                                             
          "./tsconfig.json",                                                                                                                                                                                                   
          "../../../common/tools/eslint-plugin-azure-sdk/tsconfig.lintjson.json",                                                                                                                                              
        ]                                                                                                                                                                                                                      
```
ESLint gives errors like below, seems that there's some disconnection between markdown blocks and ts projects, as the ignore pattern of `"**/generated/**"` worked as expected as they are part of ts projects.

**Comment by jeremymeng** [comment]
https://github.com/Azure/azure-sdk-for-js/pull/21061#issuecomment-1098661882

**Comment by btmills** [comment]
See the [TypeScript example](https://github.com/eslint/eslint-plugin-markdown/tree/main/examples/typescript) for reference. Type-aware rules are not supported in code blocks because the TypeScript compiler cannot see them. If you remove the `project` setting from code blocks, the non-type-aware rules should work.

**Comment by jeremymeng** [comment]
We still want the `project` setting for linting normal ts projects.  We have an override for JavaScript code blocks.  For now I don't need to link TypeScript code blocks and am trying to exclude them.

https://github.com/Azure/azure-sdk-for-js/blob/3f66fe82eee17385bcfeed1b09a75820cc7b09d0/common/tools/eslint-plugin-azure-sdk/src/configs/azure-sdk-base.ts#L143

**Comment by btmills** [comment]
If you don't need to lint TS code blocks, did the ignore pattern work?

**Comment by jeremymeng** [comment]
> If you don't need to lint TS code blocks, did the ignore pattern work?

No, I have `ignorePatterns: ["**/generated/**", "**/*.md/*.{ts,json}"],` but looks that eslint is still trying to process them

68:3 error Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: README.md/3_3.json.
The file must be included in at least one of the projects provided
183:1 error Parsing error: "parserOptions.project" has been set for @typescript-eslint/parser.
The file does not match your project config: README.md/7_7.ts.
The file must be included in at least one of the projects provided

**Comment by btmills** [comment]
It's starting to smell like ESLint might not be handling ignores properly for code blocks. In theory, https://github.com/eslint/eslint/blob/413f1d55f0ad05b6fe75bdde6df423253806797d/lib/linter/linter.js#L1805 should take care of that, but your experience says otherwise. If that's the case, it's likely to be a bug in ESLint itself rather than this plugin. I'll have to look closer. If you have time, will you try to create a minimal repro, either as a standalone repository or perhaps branching off of the TS example in this repository?

**Comment by jeremymeng** [comment]
@btmills I really appreciate your help!  Here's a simpler project: https://github.com/jeremymeng/eslint-markdown-repo.  just need to run `npm lint` to see the reported errors.

**Comment by jeremymeng** [comment]
I see the `filterCodeBlock()` check reach here, https://github.com/eslint/eslint/blob/413f1d55f0ad05b6fe75bdde6df423253806797d/lib/cli-engine/file-enumerator.js#L260-L267

However, I don't see any checks against `ignorePattern` in `isAdditionalTargetPath()`?

https://github.com/eslint/eslintrc/blob/bdce01aad747393d13cd1ae17d8280e54c9c5191/lib/config-array/config-array.js#L491

**Comment by jeremymeng** [comment]
@btmills have you got a chance to have a look at the repro project?  Should I log an issue in eslint repo instead?

**Comment by btmills** [comment]
Thanks, @jeremymeng! I was able to repro this issue using your example. This does look like a bug in ESLint itself rather than this plugin, but no need to open an issue there because I'll have a standalone  PR up shortly. Using your example, I was able to put together a test case, and the fix is small.

**Comment by jeremymeng** [comment]
@btmills that's great to hear!  Looking forward to the new version!

**Comment by btmills** [comment]
@jeremymeng to stay in the loop, follow along at https://github.com/eslint/eslint/pull/15813. We're working on some pretty big config changes, so we may want to hold off on this fix to avoid giving that a moving target. That discussion will continue in that issue thread.
