### ISSUE TITLE
Usage with TypeScript and type-aware rules

### ISSUE THREAD

**Issue by alecmev** [eslint/eslint-plugin-markdown#209]
I have a relatively complicated setup, built on top of `eslint-config-auto`, so I had to come up with a way to disable all type-aware rules for `*.md` (rather than never enabling them in the first place). Thankfully, it turned out to be easy:

```js
// .eslintrc.md.js

const { rules } = require('@typescript-eslint/eslint-plugin');

module.exports = {
  parserOptions: { project: null },
  rules: Object.fromEntries(
    Object.entries(rules)
      .filter(([, rule]) => rule.meta.docs?.requiresTypeChecking)
      .map(([name]) => [`@typescript-eslint/${name}`, 0]),
  ),
};
```

```yml
# .eslintrc.yml

overrides:
  - files: '**/*.md/*.{ts,tsx,d.ts}'
    extends: './.eslintrc.md.js'
```

Posting this as an issue because I'm not sure what you'd like to do with this information. Would be nice to publish `.eslintrc.md.js` as a reusable config with a peer dependency on `@typescript-eslint/eslint-plugin`, but I suppose that's more in the wheelhouse of `@typescript-eslint` than of this project.

**Comment by nzakas** [comment]
Yeah, I’d suggest sharing with the typescript-eslint project, as it’s more about the TypeScript than it is about the Markdown.

**Comment by meteorlxy** [comment]
FYI, ts-eslint is providing a shared config `disable-type-checked`
