### ISSUE TITLE
Invitation to move to official `eslint-community` org

### ISSUE THREAD

**Issue by MichaelDeBoey** [eslint/eslint-plugin-markdown#211]
We would love to have this repo added to the official [`@eslint-community` organization on GitHub](https://github.com/eslint-community).

As you can read in [the '`@eslint-community` GitHub organization' RFC](https://github.com/eslint/rfcs/tree/main/designs/2022-community-eslint-org), the goal of this new org is to have a place where community members can help ensure widely depended upon ESLint related packages stay up to date with newer ESLint releases and doesn't hold the wider community back without depending on one person's GitHub/`npm` account.

Since this plugin is currently maintained by the ESLint TSC, it's taking time away from the main repo & responsibilities from the team.
That's why we think it's a good idea to transfer this repo to a better home, so you're welcome to transfer this repository to the new org.

**Comment by nzakas** [comment]
I’m not sure we actually can transfer this over. Because this is part of the Open JS IP, it requires the Open JS CLA be signed for all contributions, and that bot only works on a per-org basis, not a per-repo basis.

So we either need to leave the repo where it is or else create a separate fork in the eslint-community org that would effectively be a different package. For the time being, it seems like leaving things as-is is the best choice.

**Comment by MichaelDeBoey** [comment]
How would this impact extracting things for the main repo, like we did in v8 with `eslint-formatter-codeframe` & `eslint-formatter-table`?

**Comment by snitin315** [comment]
@nzakas @MichaelDeBoey For webpack, we have set up Open JS CLA for both [webpack](https://github.com/webpack) and [webpack-contrib organization](https://github.com/webpack-contrib). Maybe we can enable the CLA bot for eslint-community similarly.

**Comment by nzakas** [comment]
@MichaelDeBoey when other folks extract code from our repo and set up a different repo (which they are allowed to do by the license), that becomes a separate project that can be run separately. It’s the transferring of an existing repo that brings over all the overhead. 

@snitin315 my understanding is that the Open JS CLA checker applied to every repo in an org, you can’t just pick one or two.

**Comment by snitin315** [comment]
@nzakas yes it'll be applied to all repositories. @MichaelDeBoey Is it possible to move other repositories under Open JS?

**Comment by MichaelDeBoey** [comment]
@snitin315 If you mean if it's possible to add @eslint-community under Open JS, I don't know if we want that tbh.
That is something we should discuss together with the ESLint team

**Comment by nzakas** [comment]
Yeah, I don’t think it’s worth moving eslint-community under Open JS. There’s not a lot of value there.

**Comment by snitin315** [comment]
Let's close this one then.
