### ISSUE TITLE
request: update dependencies

### ISSUE THREAD

**Issue by blowsie** [eslint/eslint-plugin-markdown#218]
In my nuxt project this plugin is causing conflicts with `@nuxtjs/content`.
Updating this dependency should fix the issue
https://github.com/syntax-tree/mdast-util-from-markdown

**Comment by nzakas** [comment]
If you can send a pull request, we can take a look at getting it merged.

**Comment by so1ve** [comment]
Which version are you upgrading to? After v1 it is ESM only.

**Comment by JounQin** [comment]
I think we need can release a commonjs version of `mdast-util-from-markdown` like `mdast-util-from-markdown-cjs` and use it.

**Comment by JounQin** [comment]
We can use https://github.com/un-ts/synckit to use ESM only package.
