### ISSUE TITLE
plugin is not working here [problem and workaround identified inside this issue]

### ISSUE THREAD

**Issue by iambumblehead** [eslint/eslint-plugin-markdown#227]
Hello,

eslint-plugin-markdown seems to have stop working for my project about a year ago, [here.][0] I tried fiddling with the .eslintrc.json but haven't succeeded in getting the plugin to lint the README.md for the project.

The project `.eslintrc.json` is [here][1] and includes "plugin:markdown/recommended" in the "extends" list,
```
  "extends": [
    "eslint:recommended",
    "plugin:markdown/recommended"    
  ],  
```

Any suggestions or advice are welcome.

[0]: https://github.com/iambumblehead/esmock
[1]: https://github.com/iambumblehead/esmock/blob/main/.eslintrc.json

**Comment by iambumblehead** [comment]
I have found that the plugin works when I make the following change to the README
```
diff --git a/README.md b/README.md
index b8e865c..4cfbaa7 100644
--- a/README.md
+++ b/README.md
@@ -22,7 +22,7 @@ await esmock(
 ```
 
 `esmock` examples
-``` javascript
+```js
 import test from 'node:test'
 import assert from 'node:assert'
 import esmock from 'esmock'
```
The code block must not have a space between the opening backicks and the language must be specified as "js" and not "javascript"

Emacs' markdown plugin formats the codeblock as above, with the extra space character and using the full "javascript" name and I don't know which is correct, but I can update my README to the format needed by this plugin.

**Comment by iambumblehead** [comment]
This PR resolved the issue for the project https://github.com/iambumblehead/esmock/pull/275/files

**Comment by nzakas** [comment]
Thanks for the update.
