### ISSUE TITLE
Using eslint preprocessor API?

### ISSUE THREAD

**Issue by mik01aj** [eslint/eslint-plugin-markdown#25]
Does this project use the API introduced in https://github.com/eslint/eslint/issues/1817?

If not, will I not run into problems if I use this plugin with the newest ESLint?

**Comment by btmills** [comment]
Yes, it uses the preprocessor API. It should work with any version of ESLint since 0.16.0.

Sorry for the delay - apparently I missed this when it first came in.

**Comment by mik01aj** [comment]
Ok then - so why does the README say that

> Supported extensions are `.markdown`, `.mdown`, `.mkdn`, and `.md`.

While I guess it should recommend adding the following to `.eslintrc`:

    processors: {
        ".md": ...?,
        ".markdown": ...?
    }

:question:

**Comment by btmills** [comment]
The portion you're referencing is part of the plugin source. You don't need to worry about that. You just need to add it to the `plugins` section of your `.eslintrc` as shown in the readme.

**Comment by mik01aj** [comment]
Ah, now I get it. Sorry, I got confused.
