### ISSUE TITLE
Unable to install because of shasum issue on vfile + npm

### ISSUE THREAD

**Issue by geek** [eslint/eslint-plugin-markdown#47]
Seems like a npm issue, if I pull the vfile directly and shasum it the value is correct.

```sh
$ npm install eslint-plugin-markdown
npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/../.nvm/versions/node/v5.4.1/bin/node" "/Users/.../.nvm/versions/node/v5.4.1/bin/npm" "install" "eslint-plugin-markdown"
npm ERR! node v5.4.1
npm ERR! npm  v3.3.12

npm ERR! shasum check failed for /var/folders/vb/gnnlw81500xbv1j4cd9ynfv40000gn/T/npm-8903-a7884799/registry.npmjs.org/vfile/-/vfile-1.3.0.tgz
npm ERR! Expected: d272e8bb5c4adc196e6181515534ff57bfe2944f
npm ERR! Actual:   ffc1b808f0d5950e0a77bbb9c477f935324aadb0
npm ERR! From:     https://registry.npmjs.org/vfile/-/vfile-1.3.0.tgz
npm ERR!
```

Thought you should be aware of the issue... asked a friend and they could reproduce as well.

**Comment by btmills** [comment]
Some googling suggests you're probably right and it's an issue with either npm or the network. If you attempt to retry the install, does it fail in the same way again? What happens if you clean your npm cache with `npm cache clean` and then retry the install?

**Comment by btmills** [comment]
Going to close this for now since there have been no more reports. @geek post back here if the problem persists!
