### ISSUE TITLE
Impossible to satisfy `eol-last` rule

### ISSUE THREAD

**Issue by BYK** [eslint/eslint-plugin-markdown#48]
With the upgrade to `remark`, it is not impossible to enforce `eol-last` because all trailing whitespace on code blocks are removed.

May be a good idea to silence this completely internally if possible. Or at least say something about this on docs.

**Comment by btmills** [comment]
Yeah, I think it makes sense to say that rule doesn't really apply in the context of a Markdown code block.  I see two options:

1. Document this and require people to disable this rule in a Markdown-specific config. If there are other rules like this, it may be necessary.
2. Like you suggested, we can silence this internally by filtering out `eol-last` errors during postprocessing. Hopefully this option is sufficient.

Before making a decision, are there any other rules that don't apply?

**Comment by BYK** [comment]
I'd love to do 1 but until we have configuration per file/glob it doesn't look practical (or unless we can find a way to set rules inside Markdown files without using comments in code blocks) so I'd go with 2 with proper documentation.

I haven't seen any other rules yet. `no-trailing-spaces` and `no-irregular-whitespace` are other potential rules that my not be applicable.

**Comment by btmills** [comment]
I'd *really* like to be able to do 1 as well. For reference, glob-based configuration is eslint/eslint#3611. I'll post over there and see if I can help out.
