### ISSUE TITLE
Plugin does not work with autofix

### ISSUE THREAD

**Issue by tunnckoCore** [eslint/eslint-plugin-markdown#58]
ref: https://github.com/AtomLinter/linter-eslint/issues/815

Everything just started with https://github.com/AtomLinter/linter-eslint/issues/779. 

I just have a markdown file, javascript file and eslintrc.

I'm using:

```
% ❯ npm ls | grep eslint                                                                               February 12, 12:34:53
├── eslint@3.15.0
├── eslint-config-standard@6.2.1
├── eslint-plugin-markdown@1.0.0-beta.3
├── eslint-plugin-promise@3.4.1
├── eslint-plugin-standard@2.0.1
```

and have this config

```json
{
  "extends": ["standard"],
  "plugins": ["markdown"],
  "rules": {
    "semi": [
      2,
      "always"
    ]
  }
}
```

Intentionally makes `standard` to always want semicolons so it is easy to see if autofixing works.

Initially I was thinking it is Linter-ESLint bug, but seems it isn't. Because when run the following ESLint still report errors and does not fix them.

```
eslint --fix --ext md README.md
eslint --fix --ext md .
eslint --fix -c .eslintrc --ext md README.md
```

the code fences in the markdown file is both `jsx` and `js`

**Comment by platinumazure** [comment]
Plugins that use processors (that is, plugins which need to extract JavaScript snippets out of non-JavaScript files) are not able to use autofix due to architectural/design limitations we haven't yet been able to overcome. So files linted using eslint-plugin-markdown won't have autofix applied to them.

As you've noted, this is a core ESLint issue and not something restricted to editor integrations.

When I'm on a PC, I'll find the relevant issues and put them in here.

**Comment by hirokiosame** [comment]
@platinumazure Has anything changed to make this easier to add since the release of ESLint v4?

**Comment by not-an-aardvark** [comment]
No. However, this might be possible soon if https://github.com/eslint/eslint/pull/9090 is merged.

**Comment by papakai** [comment]
This got merged, so +1

**Comment by BridgeAR** [comment]
It would be very nice if this could be worked on now.

**Comment by byzyk** [comment]
Guys, I created PR #97 for this feature. Feel free to share the feedback if it works for your use cases.

**Comment by tunnckoCore** [comment]
Seems like it works, but does not writes the fixes?
