### ISSUE TITLE
Allow node fenced code blocks

### ISSUE THREAD

**Issue by devinivy** [eslint/eslint-plugin-markdown#7]
`js` and `javascript` are currently the fenced code block types that are linted.  Would you consider to support linting `node` fenced code blocks as well?

**Comment by btmills** [comment]
Based on the Linguist [languages](https://github.com/github/linguist/blob/master/lib/linguist/languages.yml) file, both `js` and [`node`](https://github.com/github/linguist/blob/58a34cdb7d722a491905e612ca20da6058b2d9c7/lib/linguist/languages.yml#L1616) are aliases for `javascript`, so we should support all three as well.
