### ISSUE TITLE
First empty line in code fragment breaks line numeration in error messages

### ISSUE THREAD

**Issue by vsemozhetbyt** [eslint/eslint-plugin-markdown#77]
Test doc:

<pre>
### Heading

```js

console.log('a')
```
</pre>

Message:

```console
  4:17  error  Missing semicolon  semi
```

This should be `5:17`.

**Comment by btmills** [comment]
[`remark-parse` v7](https://github.com/remarkjs/remark/releases/tag/remark-parse%407.0.0) includes https://github.com/remarkjs/remark/pull/423, which should fix this issue and #78.
