### ISSUE TITLE
Feature Request: Lint <script> content in HTML block

### ISSUE THREAD

**Issue by fengyuanchen** [eslint/eslint-plugin-markdown#83]
````
# Example

```html
<h1>Hello, World!</h1>

<script>
  const a = 42;
  a = 'oops'; // Error (no-const-assign): `a` is constant.
<script>

<style></style>
```
````

**Comment by vsemozhetbyt** [comment]
You can use [eslint-plugin-html](https://github.com/BenoitZugmeyer/eslint-plugin-html) for now.

**Comment by fengyuanchen** [comment]
@vsemozhetbyt Both `eslint-plugin-html` and `eslint-plugin-markdown` are used, but not work for script in HTML block.

**Comment by btmills** [comment]
@fengyuanchen do you want to lint `<script>` tags in `.html` files or in HTML markup `<script>` tags embedded in `.md` files?

**Comment by fengyuanchen** [comment]
@btmills Lint `<script>` tag content in HTML code block of `.md` files.

**Comment by zimme** [comment]
There is `eslint-plugin-script-tags`.

**Comment by btmills** [comment]
@zimme thanks for the find! Looks like `eslint-plugin-script-tags` handles this nicely.
