### ISSUE TITLE
v1.0.0-beta.7 release?

### ISSUE THREAD

**Issue by evilsoft** [eslint/eslint-plugin-markdown#86]
Looks like beta.7 was released but it looks like it was never pushed to npm.
Would really love that new skip feature!!

**Comment by Danktuary** [comment]
Hey @btmills, any ETA on when 1.0.0-beta.7 will get published to npm? 

For anybody that ran into the same issue as I did (installed via npm, tried to use the skip feature listed on the readme): you can just install directly from the repo for the time being.

```bash
$ npm install --save-dev eslint/eslint-plugin-markdown
# or if you use Yarn
$ yarn add --dev eslint/eslint-plugin-markdown
```

**Comment by btmills** [comment]
Sorry for the delay in getting to this. `1.0.0-beta.7` is published under the `next` tag, so `npm install --save-dev eslint-plugin-markdown@next` or `yarn add --dev eslint-plugin-markdown@next` should do the trick for you!
