### ISSUE TITLE
Allow number of expected errors on line

### ISSUE THREAD

**Issue by IanVS** [eslint/eslint-plugin-markdown#9]
When there are more than one error on a line, they become difficult to read:

![array-bracket-spacing_scroll](https://cloud.githubusercontent.com/assets/4616705/9538971/a0767446-4d18-11e5-8735-02473bc9aab5.png)

In some (all?) cases, it may make more sense to simply use `/*2 errors*/`, rather than specifying all the errors themselves.

**Comment by btmills** [comment]
Makes sense to me; that'll look a lot better.

**Comment by IanVS** [comment]
I'll work on this tonight.
