### ISSUE TITLE
[question/docs]: suppress `strict`

### ISSUE THREAD

**Issue by evilebottnawi** [eslint/eslint-plugin-markdown#94]
In docs often avoiding `use strict` directive. Should we suppress this by default or documentation this? Looks even https://eslint.org/ doesn't use `use strict` in docs.

**Comment by btmills** [comment]
You're right, `"use strict";` is extremely uncommon in Markdown files, so we should either suppress it or put something in the docs. The difference between it and the two always-suppressed rules (`eol-last` and `unicode-bom`) is that those two are impossible to have in a Markdown code block, whereas someone _could_ choose to follow `strict` if they really wanted to. Given that, I think it's preferable to add a bit in the readme showing how to disable `strict` just in Markdown files, something like this:

```js
// .eslintrc.json
{
	// ...
	"overrides": [{
		"files": ["**/*.md"],
		"rules": {
			"strict": "off"
		}
	}]
}
```

What do you think?

**Comment by evilebottnawi** [comment]
@btmills i think add this docs is applicable to me :+1:
